const variables = {
  ADMINREGISTER: 'ADMINREGISTER',
  ADMINLOGIN: 'ADMINLOGIN',
  GETALLSTUDENTS: 'GETALLSTUDENTS',
  ADDDEPARTMENT: 'ADDDEPARTMENT',
  GETALLDEPARTMENTS: 'GETALLDEPARTMENTS',
  ADDSUBJECT: 'ADDSUBJECT',
  UPDATEDEPARTENT: 'UPDATEDEPARTMENT',
  DELETEDEPARTMENT: 'DELETEDEPARTMENT',
}

export default variables
