const variables = {
  ADMINREGISTER: 'ADMINREGISTER',
  ADMINLOGIN: 'ADMINLOGIN',
  STUDENTLOGIN: 'STUDENTLOGIN',
  GETALLSTUDENTS: 'GETALLSTUDENTS',
  ADDDEPARTMENT: 'ADDDEPARTMENT',
  GETALLDEPARTMENTS: 'GETALLDEPARTMENTS',
  ADDSUBJECT: 'ADDSUBJECT',
  UPDATEDEPARTENT: 'UPDATEDEPARTMENT',
  DELETEDEPARTMENT: 'DELETEDEPARTMENT',
  DELETESTUDENT: 'DELETESTUDENT',
  UPDATESTUDENT: 'UPDATESTUDENT',
}

export default variables
